import { useState, useCallback, useRef } from 'react';
import { AgentTask, Tab } from '../components/types';

let _id = 0;
const AGENTS = [
  { id: 'Coder', label: 'Writer' },
  { id: 'Researcher', label: 'Reviewer' },
  { id: 'Supervisor', label: 'Nova Core' },
  { id: 'Security', label: 'Security' },
  { id: 'Performance', label: 'Perf' },
];

function escHtml(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function simulateResult(desc: string, tab: Tab | null): Pick<AgentTask, 'result' | 'diff'> {
  const d = desc.toLowerCase();
  const content = tab?.content ?? '';
  const lang = tab?.language ?? 'typescript';
  const file = tab?.name ?? 'file';

  let modified = content;
  let note = '';

  if (d.includes('log') || d.includes('console') || d.includes('print')) {
    const line = lang === 'python' ? `print("[Nova] ${desc}")\n` : `console.log("[Nova] ${desc}");\n`;
    modified = line + content;
    note = '• Inserted logging statement at top of file';
  } else if (d.includes('comment') || d.includes('doc')) {
    const hdr = lang === 'python'
      ? `"""\n${desc}\nAuto-generated by Nova Agent.\n"""\n\n`
      : `/**\n * ${desc}\n * @auto-generated by Nova\n */\n`;
    modified = hdr + content;
    note = '• Added documentation header';
  } else if (d.includes('todo') || d.includes('fix')) {
    const todo = lang === 'python' ? `# TODO: ${desc}\n` : `// TODO: ${desc}\n`;
    modified = content + '\n' + todo;
    note = '• Added TODO marker at end of file';
  } else if (d.includes('type') || d.includes('interface')) {
    const block = `\n// Nova: Generated type for "${desc}"\nexport interface GeneratedType {\n  id: string;\n  value: unknown;\n}\n`;
    modified = content + block;
    note = '• Appended generated interface';
  } else {
    const cmt = lang === 'python' ? `# Nova: ${desc}\n` : `// Nova: ${desc}\n`;
    modified = cmt + content;
    note = '• Applied requested change';
  }

  const diff = tab && content !== modified
    ? { original: content, modified, file, language: lang }
    : undefined;

  const result = `✓ Task complete\n\n${note}\n\nFile: ${file}\nAgent finished reviewing and applied changes. Click "Review Changes" to see the diff and accept or reject.`;
  return { result, diff };
}

export function useTaskQueue(activeTab: Tab | null, wsStatus: string, wsSend: (m: string) => void) {
  const [tasks, setTasks] = useState<AgentTask[]>([]);
  const timers = useRef<Record<string, ReturnType<typeof setTimeout>>>({});

  const addTask = useCallback((description: string) => {
    const id = String(++_id);
    const agent = AGENTS[_id % AGENTS.length];
    const task: AgentTask = {
      id, description, status: 'queued',
      agentId: agent.id, agentLabel: agent.label,
      createdAt: Date.now(),
    };
    setTasks(prev => [task, ...prev]);
    if (wsStatus === 'connected') wsSend(`[task] ${description}`);

    timers.current[`${id}w`] = setTimeout(() =>
      setTasks(prev => prev.map(t => t.id === id ? { ...t, status: 'working' } : t))
    , 800 + Math.random() * 400);

    timers.current[`${id}d`] = setTimeout(() => {
      const { result, diff } = simulateResult(description, activeTab);
      setTasks(prev => prev.map(t => t.id === id ? { ...t, status: 'done', result, diff } : t));
    }, 2800 + Math.random() * 1500);

    return id;
  }, [activeTab, wsStatus, wsSend]);

  const removeTask = useCallback((id: string) => {
    clearTimeout(timers.current[`${id}w`]);
    clearTimeout(timers.current[`${id}d`]);
    setTasks(prev => prev.filter(t => t.id !== id));
  }, []);

  const clearCompleted = useCallback(() =>
    setTasks(prev => prev.filter(t => t.status === 'queued' || t.status === 'working'))
  , []);

  return { tasks, addTask, removeTask, clearCompleted };
}
